export const FETCH_COUNTRIES_LOADING = 'FETCH_COUNTRIES_LOADING'
export const FETCH_COUNTRIES_SUCCESS='FETCH_COUNTRIES_SUCCESS'
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE'
export const REMOVE_COUNTRY_FROM_THE_LIST = 'REMOVE_COUNTRY_FROM_THE_LIST'